services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - knoxgym-network

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
        KC_HEALTH_ENABLED: "true"
        KC_LOG_LEVEL: info
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: ${POSTGRES_DB}
        KC_DB_USERNAME: ${POSTGRES_USER}
        KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
        interval: 15s
        timeout: 2s
        retries: 15
      command:
        [ "start-dev", "--http-port=7080", "--https-port=7443"]
      ports:
        - 7080:7080
        - 7443:7443
      depends_on:
        - postgres
      networks:
        - knoxgym-network

volumes:
  postgres_data:

networks:
  knoxgym-network: